// flow-typed signature: b8c1321bd66b9a88d604ae6d994c8314
// flow-typed version: <<STUB>>/react-fullcanvas_v1.0.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-fullcanvas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-fullcanvas' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-fullcanvas/flow-typed/npm/classnames_v2.x.x' {
  declare module.exports: any;
}

declare module 'react-fullcanvas/flow-typed/npm/minimist_v1.x.x' {
  declare module.exports: any;
}

declare module 'react-fullcanvas/flow-typed/npm/radium_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-fullcanvas/flow-typed/npm/react-hot-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-fullcanvas/flow-typed/npm/require-dir_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-fullcanvas/gulp/build' {
  declare module.exports: any;
}

declare module 'react-fullcanvas/gulp/copy' {
  declare module.exports: any;
}

declare module 'react-fullcanvas/gulp/default' {
  declare module.exports: any;
}

declare module 'react-fullcanvas/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'react-fullcanvas/lib/babel' {
  declare module.exports: any;
}

declare module 'react-fullcanvas/lib/react-fullcanvas' {
  declare module.exports: any;
}

declare module 'react-fullcanvas/src/app' {
  declare module.exports: any;
}

declare module 'react-fullcanvas/src/component/FullCanvas/index' {
  declare module.exports: any;
}

declare module 'react-fullcanvas/src/index' {
  declare module.exports: any;
}

declare module 'react-fullcanvas/test/index' {
  declare module.exports: any;
}

declare module 'react-fullcanvas/test/setup' {
  declare module.exports: any;
}

declare module 'react-fullcanvas/webpack.config.babel' {
  declare module.exports: any;
}

declare module 'react-fullcanvas/webpack/dev' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-fullcanvas/flow-typed/npm/classnames_v2.x.x.js' {
  declare module.exports: $Exports<'react-fullcanvas/flow-typed/npm/classnames_v2.x.x'>;
}
declare module 'react-fullcanvas/flow-typed/npm/minimist_v1.x.x.js' {
  declare module.exports: $Exports<'react-fullcanvas/flow-typed/npm/minimist_v1.x.x'>;
}
declare module 'react-fullcanvas/flow-typed/npm/radium_vx.x.x.js' {
  declare module.exports: $Exports<'react-fullcanvas/flow-typed/npm/radium_vx.x.x'>;
}
declare module 'react-fullcanvas/flow-typed/npm/react-hot-loader_vx.x.x.js' {
  declare module.exports: $Exports<'react-fullcanvas/flow-typed/npm/react-hot-loader_vx.x.x'>;
}
declare module 'react-fullcanvas/flow-typed/npm/require-dir_vx.x.x.js' {
  declare module.exports: $Exports<'react-fullcanvas/flow-typed/npm/require-dir_vx.x.x'>;
}
declare module 'react-fullcanvas/gulp/build.js' {
  declare module.exports: $Exports<'react-fullcanvas/gulp/build'>;
}
declare module 'react-fullcanvas/gulp/copy.js' {
  declare module.exports: $Exports<'react-fullcanvas/gulp/copy'>;
}
declare module 'react-fullcanvas/gulp/default.js' {
  declare module.exports: $Exports<'react-fullcanvas/gulp/default'>;
}
declare module 'react-fullcanvas/gulpfile.babel.js' {
  declare module.exports: $Exports<'react-fullcanvas/gulpfile.babel'>;
}
declare module 'react-fullcanvas/lib/babel.js' {
  declare module.exports: $Exports<'react-fullcanvas/lib/babel'>;
}
declare module 'react-fullcanvas/lib/react-fullcanvas.js' {
  declare module.exports: $Exports<'react-fullcanvas/lib/react-fullcanvas'>;
}
declare module 'react-fullcanvas/src/app.js' {
  declare module.exports: $Exports<'react-fullcanvas/src/app'>;
}
declare module 'react-fullcanvas/src/component/FullCanvas/index.js' {
  declare module.exports: $Exports<'react-fullcanvas/src/component/FullCanvas/index'>;
}
declare module 'react-fullcanvas/src/index.js' {
  declare module.exports: $Exports<'react-fullcanvas/src/index'>;
}
declare module 'react-fullcanvas/test/index.js' {
  declare module.exports: $Exports<'react-fullcanvas/test/index'>;
}
declare module 'react-fullcanvas/test/setup.js' {
  declare module.exports: $Exports<'react-fullcanvas/test/setup'>;
}
declare module 'react-fullcanvas/webpack.config.babel.js' {
  declare module.exports: $Exports<'react-fullcanvas/webpack.config.babel'>;
}
declare module 'react-fullcanvas/webpack/dev.js' {
  declare module.exports: $Exports<'react-fullcanvas/webpack/dev'>;
}
